[project]
name = "espresso-horoscope-mcp"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = ["typer>=0.12","pyyaml>=6.0","jinja2>=3.1","fastapi>=0.115","uvicorn>=0.30","orjson>=3.10","rich>=13.7","requests>=2.31"]
